import type { Metadata } from "next";
import { Rubik, Overpass } from "next/font/google";
import "./globals.css";
import TheFooter from "./_ui/the-footer";
import TheHeader from "./_ui/the-header";

const rubik = Rubik({ subsets: ["latin"] });
const overpass = Overpass({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <TheHeader />
        {children}
        <TheFooter />
      </body>
    </html>
  );
}
